---
name: dlrover-trainer-test
description: run pytest to execute python test cases of dlrover-trainer
runs:
  using: 'docker'
  image: "easydl/easydl:ci"
  args:
    - "/bin/bash"
    - "-c"
    - "pip install pyhocon && python -m pytest dlrover/trainer/tests"
