apiVersion: elastic.iml.github.io/v1alpha1
kind: ScalePlan
metadata:
  name: deepctr-sample-auto-scaling-116
  labels:
    elasticjob-name: deepctr-sample-auto-scaling-114
    scale-type: manual
spec:
  ownerJob: deepctr-sample-auto-scaling-114
  replicaResourceSpecs:
    worker:
      replicas: 1
