apiVersion: elastic.iml.github.io/v1alpha1
kind: ScalePlan
metadata:
  name: deepctr-sample-auto-scaling-102
  labels:
    elasticjob-name: deepctr-sample-auto-scaling-101
    scale-type: manual
spec:
  ownerJob: deepctr-sample-auto-scaling-101
  replicaResourceSpecs:
    worker:
      replicas: 1
