apiVersion: elastic.iml.github.io/v1alpha1
kind: ElasticJob
metadata:
  name: elasticjob-sample
spec:
  distributionStrategy: ParameterServerStrategy
  replicaSpecs:
    ps:
      replicas: 1
      restartCount: 3
      template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            restartPolicy: Never
            containers:
              - name: main
                image: elasticdl:iris_estimator
                command:
                  - /bin/bash
                  - -c
                  - "pip install http://armor-test.oss-cn-hangzhou-zmf.aliyuncs.com/apps/elasticdl/dlrover-0.1.0rc0.dev0-py3-none-any.whl -I --no-deps && python -m model_zoo.iris.dnn_estimator --batch_size=32 --training_steps=1000"
                resources:
                  requests:
                    cpu: "0.5"
                    memory: 256Mi
    chief:
      replicas: 1
      restartCount: 3
      template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            restartPolicy: Never
            containers:
              - name: main
                image: elasticdl:iris_estimator
                command:
                  - /bin/bash
                  - -c
                  - "pip install http://armor-test.oss-cn-hangzhou-zmf.aliyuncs.com/apps/elasticdl/dlrover-0.1.0rc0.dev0-py3-none-any.whl -I --no-deps && python -m model_zoo.iris.dnn_estimator --batch_size=32 --training_steps=1000"
                resources:
                  requests:
                    cpu: "0.5"
                    memory: 256Mi
    worker:
      replicas: 2
      restartCount: 3
      template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            restartPolicy: Never
            containers:
              - name: main
                image: elasticdl:iris_estimator
                command:
                  - /bin/bash
                  - -c
                  - "pip install http://armor-test.oss-cn-hangzhou-zmf.aliyuncs.com/apps/elasticdl/dlrover-0.1.0rc0.dev0-py3-none-any.whl -I --no-deps && python -m model_zoo.iris.dnn_estimator --batch_size=32 --training_steps=1000"
                resources:
                  requests:
                    cpu: "0.5"
                    memory: 256Mi
