apiVersion: elastic.iml.github.io/v1alpha1
kind: ElasticJob
metadata:
  name: elasticjob-sample
spec:
  distributionStrategy: ParameterServerStrategy
  resourceLimits:
    cpu: "6"
    memory: "8192Mi"
  replicaSpecs:
    ps:
      restartCount: 3
      template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            restartPolicy: Never
            containers:
              - name: main
                image: elasticdl:iris_estimator
                imagePullPolicy: IfNotPresent
                command:
                  - /bin/bash
                  - -c
                  - "python -m model_zoo.tf_estimator.iris_dnn_elastic"
    worker:
      replicas: 0
      restartCount: 3
      template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            restartPolicy: Never
            containers:
              - name: main
                image: elasticdl:iris_estimator
                imagePullPolicy: IfNotPresent
                command:
                  - /bin/bash
                  - -c
                  - "python -m model_zoo.tf_estimator.iris_dnn_elastic"
